<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="INNOPHLTXE3E140" failures="2" tests="5" name="Default test(failed)(failed)(failed)" time="0.135" errors="0" timestamp="2024-01-21T21:59:48 IST">
  <testcase classname="testNGTests.retryFailedTests" name="B" time="0.026">
    <skipped/>
  </testcase> <!-- B -->
  <testcase classname="testNGTests.retryFailedTests" name="B" time="0.002">
    <skipped/>
  </testcase> <!-- B -->
  <testcase classname="testNGTests.retryFailedTests" name="B" time="0.002">
    <skipped/>
  </testcase> <!-- B -->
  <testcase classname="testNGTests.retryFailedTests" name="B" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGTests.retryFailedTests.B(retryFailedTests.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- B -->
  <testcase classname="testNGTests.retryFailedTests" name="C" time="0.003">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testNGTests.retryFailedTests.C(retryFailedTests.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- C -->
  <testcase classname="testNGTests.retryFailedTests" name="A" time="0.0">
    <ignored/>
  </testcase> <!-- A -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
